name: Daily Node.js Job

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight

  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: node update.js

      - name: Commit rules
        run: |
          git add .
          git config --global user.name 'GrahamSH-LLK'
          git config --global user.email 'grahamsh-llk@users.noreply.github.com'
          git commit -am "Automated rules update"
          git push
