name: Daily Node.js Job

on:
  schedule:
    - cron: "5 10 * * *" # Run every day at 5:05 PM, latest most updates will be published

  workflow_dispatch:

jobs:
  run-node-script:
    strategy:
      matrix:
        ftc: [false, true]
        year: [2025]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Node.js script
        run: npm run rules:update
        env:
          FTC: ${{ matrix.ftc }}
          YEAR: ${{ matrix.year }}
